defmodule Euler.Exercise_029 do
  @moduledoc """
  Consider all integer combinations of a ** b for 2 <= a <= 5 and 2 <= b <= 5.
  If they are placed in numerical order, with any repeats removed, we get the following sequence of
  distinct terms:
  4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125.

  How many distinct terms are in the sequence generated by a ** b for 2 <= a <= 100 and 2 <= b <= 100?
  """

  def solution(upper \\ 100) do
    for a <- 2..upper, b <- 2..upper do
      a ** b
    end
    |> Enum.uniq()
    |> length()
  end
end
